import 'package:flutter/material.dart';
import 'package:frontend/components/GroupContent.dart';
import 'package:frontend/components/JoinOrCreateGroup.dart';
import 'package:frontend/pages/HomePage.dart';

class GroupPage extends StatefulWidget {
  const GroupPage({Key? key}) : super(key: key);

  @override
  // ignore: library_private_types_in_public_api
  _GroupPageState createState() => _GroupPageState();
}

class _GroupPageState extends State<GroupPage> {
  bool isInGroup = false;
  String? groupCode;
  List<Map<String, dynamic>> groupMembers =
      []; // This should be fetched from your backend or service

  void _createGroup() {
    setState(() {
      isInGroup = true;
      groupCode = '123456'; // This should be generated by your backend
    });
  }

  void _joinGroup() {
    setState(() {
      isInGroup = true;
      groupCode = '123456'; // This should be fetched from your backend
    });
  }

  void _leaveGroup() {
    showDialog(
      context: context,
      builder: (context) {
        return AlertDialog(
          title: const Text('Leave Group'),
          content: const Text('Are you sure you want to leave the group?'),
          actions: <Widget>[
            TextButton(
              child: const Text('Cancel'),
              onPressed: () {
                Navigator.of(context).pop();
              },
            ),
            TextButton(
              child: const Text('Leave'),
              onPressed: () {
                // Implement logic to handle group leaving, likely involving a call to your backend service
                setState(() {
                  isInGroup = false;
                  groupCode = null;
                  groupMembers.clear();
                });
                Navigator.of(context).pop();
              },
            ),
          ],
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        backgroundColor: Colors.black,
        elevation: 0,
        leading: const SizedBox(),
        title: const Padding(
          padding: EdgeInsets.symmetric(horizontal: 8),
          child: Text('App Title',
              style: TextStyle(
                  fontWeight: FontWeight.bold,
                  color: Color.fromARGB(255, 250, 250, 250))),
        ),
        actions: [
          Padding(
            padding: const EdgeInsets.only(right: 18),
            child: IconButton(
              icon: const Icon(Icons.arrow_forward,
                  color: Color.fromARGB(255, 250, 250, 250), size: 28),
              onPressed: () {
                Navigator.push(
                  context,
                  PageRouteBuilder(
                    pageBuilder: (context, animation1, animation2) =>
                        const HomePage(),
                    transitionDuration: Duration.zero,
                  ),
                );
              },
              splashColor: Colors.transparent,
              splashRadius: 0.1,
            ),
          ),
        ],
        centerTitle: true,
      ),
      body: isInGroup
          ? GroupContentWidget(
              groupCode: groupCode,
              groupMembers: groupMembers,
              onLeaveGroup: _leaveGroup,
            )
          : JoinOrCreateGroupWidget(
              onCreateGroup: _createGroup,
              onJoinGroup: _joinGroup,
            ),
    );
  }
}
